gui:
  # -- COLORSCHEME -- #
  theme:
    activeBorderColor:
      - "#89dceb"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89dceb"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
  # -- LAYOUT -- #
  windowSize: "normal" # normal, half, full
  sidePanelWidth: 0.25 # 0 - 1
  expandFocusedSidePanel: true
  language: "en"
  timeFormat: "02/01 - 15/04"
  # -- GIT -- #
  commitLength:
    show: true
  skipDiscardChangeWarning: true
  skipStashWarning: true
  showFileTree: true
  showListFooter: false
  showRandomTip: false
  experimentalShowBranchHeads: true
  showBottomLine: false
  showCommandLog: true
  commandLogSize: 8
  showIcons: true
  splitDiff: "always" # always, auto
  mouseEvents: false # disable mouse
